version: '3.8'

services:
  nginx:
    container_name: ma_nginx
    image: nginx:1.19
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - annotator_network
      - elucidate_network
      - textrepo_network
    ports:
      - "8000:8000"
    depends_on:
      - annotator

  annotator:
    container_name: ma_annotator
    image: micro-annotator-gui:latest
    build: ./gui
    volumes:
      - ./gui/public:/annotator/public
      - ./gui/src:/annotator/src
      - ./gui/tsconfig.json:/annotator/tsconfig.json
    networks:
      - annotator_network
    environment:
      REACT_APP_CREATOR: ${REACT_APP_CREATOR}
      REACT_APP_ELUCIDATE_HOST: http://localhost:8000/elucidate
      REACT_APP_PLACEHOLDER_SEARCH_ID: ${REACT_APP_PLACEHOLDER_SEARCH_ID}
      REACT_APP_TEXTREPO_HOST: http://localhost:8000/textrepo
    command: npm start
    expose:
      - 3000

networks:
  annotator_network:
  elucidate_network:
    external: true
    name: elucidate_network
  textrepo_network:
    external: true
    name: textrepo_network
