version: '3.8'

services:

  elucidate:
    container_name: elucidate
    image: registry.diginfra.net/bramb/huc-elucidate-server:1.6.0-SNAPSHOT
    networks:
      - elucidate_network
    env_file:
      - elucidate.env
    depends_on:
      - database
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ../../scripts/wait-for-it.sh:/scripts/wait-for-it.sh
    command: ["/scripts/wait-for-it.sh", "database:5432", "--", "./bin/catalina.sh", "run"]

  database:
    container_name: elucidate_db
    image: registry.diginfra.net/micro-annotator/elucidate-db:${COLLECTION_TAG}
    shm_size: 1g
    networks:
      - elucidate_network
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    restart: unless-stopped

networks:
  elucidate_network:
    name: elucidate_network
