version: '3.8'

services:

  elucidate:
    container_name: elucidate
    build: /Users/sebastiaanvandaalen/Work/Projects/micro-annotator_experiment/elucidate-server/elucidate-server
    networks:
      - elucidate_network
    env_file:
      - elucidate.env
    depends_on:
      - database
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ../../scripts/wait-for-it.sh:/scripts/wait-for-it.sh
    command: ["/scripts/wait-for-it.sh", "database:5432", "--", "./bin/catalina.sh", "run"]

  database:
    container_name: elucidate_db
    build: .
    shm_size: 1g
    networks:
      - elucidate_network
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    restart: unless-stopped

networks:
  elucidate_network:
    name: elucidate_network
