import Config from "../Config";

export default class Elucidate {
  static readonly host = Config.ELUCIDATE_HOST;

  static async createCollection(): Promise<string> {
    const body = {
      "@context": ["http://www.w3.org/ns/anno.jsonld", "http://www.w3.org/ns/ldp.jsonld"],
      "type": ["BasicContainer", "AnnotationCollection"],
      "label": "Autogenerated container"
    };
    const res = await fetch(`${this.host}/annotation/w3c/`, {
      method: "POST",
      headers: {
        "Accept": "application/ld+json; profile=\"http://www.w3.org/ns/anno.jsonld\"",
        "Content-Type": "application/ld+json; profile=\"http://www.w3.org/ns/anno.jsonld\""
      },
      body: JSON.stringify(body)
    });
    const responseBody = await res.json();
    let uuid = responseBody.id.split('/').filter((e: string) => !!e).pop();
    return uuid;
  }
}
