version: '3.8'
# docker-compose file for production setup
# -> uses production volumes for production data

services:

  textrepo-app:
    container_name: tr_textrepo
    image: registry.diginfra.net/micro-annotator/textrepo-app:txt_anchor
    expose:
      - 8080
      - 8081
    networks:
      - textrepo_network
    volumes:
      - ../../scripts/wait-for-it.sh:/textrepo-app/wait-for-it.sh
    command: [
        "./start.sh"
    ]
    environment:
      TR_DATABASE_DRIVER_CLASS: ${TR_DATABASE_DRIVER_CLASS}
      TR_DATABASE_USER: ${TR_DATABASE_USER}
      TR_DATABASE_PASSWORD: ${TR_DATABASE_PASSWORD}
      TR_DATABASE_URL: ${TR_DATABASE_URL}
      TR_DATABASE_PROPERTIES_CHAR_SET: ${TR_DATABASE_PROPERTIES_CHAR_SET}
      TR_DATABASE_MAX_WAIT_FOR_CONNECTION: ${TR_DATABASE_MAX_WAIT_FOR_CONNECTION}
      TR_DATABASE_VALIDATION_QUERY_TIMEOUT: ${TR_DATABASE_VALIDATION_QUERY_TIMEOUT}
      TR_DATABASE_MIN_SIZE: ${TR_DATABASE_MIN_SIZE}
      TR_DATABASE_MAX_SIZE: ${TR_DATABASE_MAX_SIZE}
      TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE: ${TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE}
      TR_DATABASE_EVICTION_INTERVAL: ${TR_DATABASE_EVICTION_INTERVAL}
      TR_LOGGING_LEVEL: ${TR_LOGGING_LEVEL}
      TR_LOGGING_LOGGERS: ${TR_LOGGING_LOGGERS}
      TR_LOGGING_APPENDERS: ${TR_LOGGING_APPENDERS}
      TR_INDEXERS: ${TR_INDEXERS}
      TR_SWAGGER_RESOURCE_PACKAGE: ${TR_SWAGGER_RESOURCE_PACKAGE}
      TR_SWAGGER_CONTEXT_ROOT: ${TR_SWAGGER_CONTEXT_ROOT}
      TR_SWAGGER_SCHEMES: ${TR_SWAGGER_SCHEMES}
      TR_PAGINATION_DEFAULT_OFFSET: ${TR_PAGINATION_DEFAULT_OFFSET}
      TR_PAGINATION_DEFAULT_LIMIT: ${TR_PAGINATION_DEFAULT_LIMIT}
      TR_DATE_FORMAT: ${TR_DATE_FORMAT}
      TR_CONTENT_DECOMPRESSION_LIMIT: ${TR_CONTENT_DECOMPRESSION_LIMIT}
      TR_FLYWAY_CLEAN_DISABLED: ${TR_FLYWAY_CLEAN_DISABLED}
      TR_FLYWAY_LOCATIONS: ${TR_FLYWAY_LOCATIONS}

  postgres:
    container_name: tr_postgres
    image: registry.diginfra.net/micro-annotator/textrepo-db:${COLLECTION_TAG}
    shm_size: 1g
    networks:
      - textrepo_network
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: /var/lib/textrepo/data

networks:
  textrepo_network:
    name: textrepo_network
