version: '3.5'
# docker-compose file for production setup
# -> uses production volumes for production data

services:
  postgres:
    container_name: tr_postgres
    image: postgres:11-alpine
    shm_size: 1g
    networks:
      - textrepo_network
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres.textrepo
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: /var/lib/textrepo/data
    volumes:
      - postgresdata-prod:/var/lib/textrepo/data

  elasticsearch:
    container_name: tr_elasticsearch
    image: knawhuc/textrepo-elasticsearch:${DOCKER_TAG}
    environment:
      - node.name=${ES_NODE_NAME}
      - cluster.initial_master_nodes=${ES_CLUSTER_INITIAL_MASTER_NODES}
      - cluster.name=${ES_CLUSTER_NAME}
      - bootstrap.memory_lock=${ES_BOOTSTRAP_MEMORY_LOCK}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - path.repo=/snapshot-repo
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-prod:/usr/share/elasticsearch/data
      - essnapshotdata-prod:/snapshot-repo
    ports:
      - 9200
    networks:
      - textrepo_network

  file-indexer:
    container_name: tr_file_indexer
    image: knawhuc/textrepo-file-indexer:${DOCKER_TAG}
    ports:
      - 8080
    networks:
      - textrepo_network
    environment:
      INTERNAL_TR_HOST: ${INTERNAL_TR_HOST}
      TR_DATE_FORMAT: ${TR_DATE_FORMAT}
    volumes:
      - ../../scripts/wait-for-it.sh:/indexer/wait-for-it.sh
    command: [
        "./wait-for-it.sh", "tr_elasticsearch:9200", "--timeout=0", "--",
        "./start.sh"
    ]

  textrepo-app:
    container_name: tr_textrepo
    image: knawhuc/textrepo-app:${DOCKER_TAG}
    expose:
      - 8080
      - 8081
    networks:
      - textrepo_network
    volumes:
      - ../../scripts/wait-for-it.sh:/textrepo-app/wait-for-it.sh
    command: [
        "./wait-for-it.sh", "file-indexer:8080", "--timeout=0", "--",
        "./start.sh"
    ]
    environment:
      TR_DATABASE_DRIVER_CLASS: ${TR_DATABASE_DRIVER_CLASS}
      TR_DATABASE_USER: ${TR_DATABASE_USER}
      TR_DATABASE_PASSWORD: ${TR_DATABASE_PASSWORD}
      TR_DATABASE_URL: ${TR_DATABASE_URL}
      TR_DATABASE_PROPERTIES_CHAR_SET: ${TR_DATABASE_PROPERTIES_CHAR_SET}
      TR_DATABASE_MAX_WAIT_FOR_CONNECTION: ${TR_DATABASE_MAX_WAIT_FOR_CONNECTION}
      TR_DATABASE_VALIDATION_QUERY_TIMEOUT: ${TR_DATABASE_VALIDATION_QUERY_TIMEOUT}
      TR_DATABASE_MIN_SIZE: ${TR_DATABASE_MIN_SIZE}
      TR_DATABASE_MAX_SIZE: ${TR_DATABASE_MAX_SIZE}
      TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE: ${TR_DATABASE_CHECK_CONNECTION_WHILE_IDLE}
      TR_DATABASE_EVICTION_INTERVAL: ${TR_DATABASE_EVICTION_INTERVAL}
      TR_LOGGING_LEVEL: ${TR_LOGGING_LEVEL}
      TR_LOGGING_LOGGERS: ${TR_LOGGING_LOGGERS}
      TR_LOGGING_APPENDERS: ${TR_LOGGING_APPENDERS}
      TR_INDEXERS: ${TR_INDEXERS}
      TR_SWAGGER_RESOURCE_PACKAGE: ${TR_SWAGGER_RESOURCE_PACKAGE}
      TR_SWAGGER_CONTEXT_ROOT: ${TR_SWAGGER_CONTEXT_ROOT}
      TR_SWAGGER_SCHEMES: ${TR_SWAGGER_SCHEMES}
      TR_PAGINATION_DEFAULT_OFFSET: ${TR_PAGINATION_DEFAULT_OFFSET}
      TR_PAGINATION_DEFAULT_LIMIT: ${TR_PAGINATION_DEFAULT_LIMIT}
      TR_DATE_FORMAT: ${TR_DATE_FORMAT}
      TR_CONTENT_DECOMPRESSION_LIMIT: ${TR_CONTENT_DECOMPRESSION_LIMIT}
      TR_FLYWAY_CLEAN_DISABLED: ${TR_FLYWAY_CLEAN_DISABLED}
      TR_FLYWAY_LOCATIONS: ${TR_FLYWAY_LOCATIONS}

networks:
  textrepo_network:
    external: false
    name: textrepo_network

volumes:
  esdata-prod:
    driver: local
  essnapshotdata-prod:
    driver: local
  postgresdata-prod:
    driver: local
